include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - camel_case_types
    - camel_case_extensions
    - library_names
    - library_prefixes
    - no_leading_underscores_for_library_prefixes
    - no_leading_underscores_for_local_identifiers
    - prefer_adjacent_string_concatenation
    - prefer_final_fields
    - prefer_final_locals
    - unnecessary_const
    - unnecessary_constructor_name

analyzer:
  exclude: [build/**]
